name: moralar_widgets
description: A new Flutter package project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  mask_text_input_formatter: ^2.0.0
  get: 4.3.4
  validatorless: ^1.2.0
  mega_flutter:
    git:
      url: git@github.com:megaleios-git/mega-flutter
      ref: v0.1.1
  flutter:
    sdk: flutter

    

dev_dependencies:
  lints: 1.0.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  fonts:
    - family: SFProText
      fonts:
        - asset: ./assets/fonts/SFProText-Regular.ttf
        - asset: ./assets/fonts/SFProText-Semibold.ttf
          weight: 700
  assets:
    - assets/images/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
